// <auto-generated />
using System;
using EmpMangSys.Repository.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpMangSys.Repository.DataBaseContext.DataMigration
{
    [DbContext(typeof(BadrGroupDbContext))]
    [Migration("20260306005602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpMangSys.Core.Data.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7145),
                            Description = "Human Resources",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7579),
                            Description = "Information Technology",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7582),
                            Description = "Financial Department",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("EmpMangSys.Core.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7815),
                            DepartmentId = 3,
                            Email = "HamzaAbdelkarim@gmail.com",
                            FullName = "Hamza Abdelkarim",
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "01002594587",
                            Salary = 32000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7823),
                            DepartmentId = 1,
                            Email = "LailaAbdelkarim@gmail.com",
                            FullName = "Laila Abdelkarim",
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "01002003330",
                            Salary = 25000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7827),
                            DepartmentId = 2,
                            Email = "NourAbdelkarim@gmail.com",
                            FullName = "Nour Abdelkarim",
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "01001004499",
                            Salary = 32000m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 55, 59, 298, DateTimeKind.Local).AddTicks(7829),
                            DepartmentId = 1,
                            Email = "JasminAbdelkarim@gmail.com",
                            FullName = "Jasmin Abdelkarim",
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "01022594587",
                            Salary = 22000m
                        });
                });

            modelBuilder.Entity("EmpMangSys.Core.Data.Employee", b =>
                {
                    b.HasOne("EmpMangSys.Core.Data.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmpMangSys.Core.Data.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
